Make GroupActions collapsible
OpenCircuits/OpenCircuits pull request #1001
Opened 2022-02-15 21:20 UTC by jssunray34

I added a state variable to track whether each GroupAction should be collapsed or not. I also added a chevron button to modify this state when clicked.

Fixes #975

2022-02-24 03:02 UTC, TGCrystal requested changes
Aside from the one minor code nitpick, I think this could be merged now. However, I think there are a few small changes that should be made to improve it a little further. These changes are not set in stone either, you should run them by @LeonMontealegre as well. (Edit: I checked with Leon, he said these changes would all make sense)

- The chevron should be on the right side, like so:
  - ![Untitled](https://user-images.githubusercontent.com/29614966/155447966-e6e4056d-3400-4d60-b079-6e6909178f2d.png)
- The chevron should be slightly larger so that its height is that of other letters in the text like the `r`, `o`, and `u` of `Group`
- Clicking anywhere in the `GroupAction ›` "row" should apply the collapse/expansion, not just the `>`. I think that is more intuitive, and would also make tapping it easier on mobile. Note that when the action is expanded, it should **not** be closed when any of the subactions are pressed. For example, in the following screenshot, clicking any of the `Placed Clock` actions should not collapse the `GroupAction`.
  - ![image](https://user-images.githubusercontent.com/29614966/155448781-080c6824-312d-474f-8860-7f1ade2ecee9.png)
- The chevron should rotate downwards when the action is expanded. If you want an example on how to do this, see the code for the button in the itemnav that transforms between the button to close and the button to open it. Specifically,
  - https://github.com/OpenCircuits/OpenCircuits/blob/master/src/site/shared/containers/ItemNav/index.tsx#L212
  - https://github.com/OpenCircuits/OpenCircuits/blob/master/src/site/shared/containers/ItemNav/index.scss#L169-L200

These are all things I probably should have put in the initial issue, sorry to dump them on you after the fact.

2022-02-24 15:15 UTC, LeonMontealegre commented on src/site/shared/containers/HistoryBox/index.tsx
> +            <span className="historybox__groupentrycollapse" onClick={() => setIsCollapsed(!isCollapsed)}>&rsaquo;</span>
nit: call it `historybox__groupentry-collapse` (and edit the corresponding SCSS name as well)

2022-03-04 21:23 UTC, jssunray34 commented
I was not able to find a very good downward-facing chevron, so let me know if you'd like me to change this icon or its positioning. Also, I believe the chevron is the same font size as the adjacent text, but I can make it larger if needed.

2022-03-04 22:01 UTC, TGCrystal commented
You can actually use the same chevron and the `transform: rotate(90deg);` css property to rotate it to point downwards. You can have that property be part of a class that is only applied when your state variable `isCollapsed` is false. Combined with the `transition: 0.5s;` property, it will even automatically perform a smooth animation while rotating down. This is how the button to open the itemnav rotates and moves from a plus sign to an X to close it. My original comment has links that should take you right to the relevant parts of the itemnav code. If you need any further help with figuring it out, don't hesitate to let me know!

As for the font size, you can leave that as is. It looks good now that it isn't right next to the text.

2022-03-04 22:05 UTC, jssunray34 commented
Oh got it! Sorry I didn't look very closely at the links you provided.

2022-03-06 03:44 UTC, TGCrystal approved these changes

2022-03-18 16:59 UTC, LeonMontealegre approved these changes

2022-03-18 18:27 UTC, merged