Add more context buttons
OpenCircuits/OpenCircuits pull request #1015
Opened 2022-02-25 22:41 UTC by shadowluigi27

Added three additional context menu operations using the event handlers. These functions are separated from the other menu operations with a line for clarity.

![image](https://user-images.githubusercontent.com/72285616/155809358-c661fca7-98e3-41c3-9679-db7d9c03c074.png)

2022-02-27 21:40 UTC, TGCrystal requested changes

2022-02-27 21:40 UTC, TGCrystal commented on src/site/shared/containers/ContextMenu/index.tsx
> +
nit: this extra newline probably isn't necessary

2022-02-28 22:05 UTC, TGCrystal approved these changes

2022-03-18 17:04 UTC, LeonMontealegre approved these changes

2022-03-18 18:27 UTC, merged