History box improvements
OpenCircuits/OpenCircuits pull request #1016
Opened 2022-02-27 12:09 UTC by EricW123

Maybe I'll continue work on other issues mentioned in #971 , so they'll all be posted in this branch
Now history box is draggable and resizzable.
Fixes #972

2022-02-27 22:34 UTC, TGCrystal requested changes
Overall, this is looking great so far! I did notice a few technical bugs and a few things for further design consideration.

- The main issue is this does not seem to work on mobile. Tested in Safari on iOS 15, dragging the header does not move the history box. I was not able to test resizing because the bottom of the history box was cutoff.
- When in portrait mode (the itemnav is on the bottom) the height of the history box is locked and cannot be resized.


As for design considerations, it is probably best to consult @LeonMontealegre on these to make sure he agrees/approves:

- Comparing on Chrome (left) vs. Firefox (right) in the screenshot below, there are some visual discrepancies. I think the look on Chrome for the scrollbar is better (rounded corners, no buttons on top/bottom). As for the resize icon, the grey and larger version of Firefox looks better. Making these things consistent across browsers can range from annoying to nearly impossible, so if completely standardizing those isn't possible, that is fine.
  - ![image](https://user-images.githubusercontent.com/29614966/155902219-c1d2b2a5-7634-4e44-8e4a-37af2b9f3f76.png)
- I think you should be able to resize using any corner/edge of the history box, similar to how you would with a window on a computer.
- Currently, the history box can cover up the header and itemnav. I don't think it should be able to cover up the header, I'm not sure if it should cover up the itemnav.
- While not a requirement, I think a button to reset the size/position of the history box could be useful. There is space for it in the history box header between the word History and the X to close it, but I'm not sure what icon would look good there, if any. Another possibility is resetting the position/size every time the history box is opened, but I think the current behavior of keeping the last used position/size makes more sense.

One last thing: Generally, it is preferred that each pr does one "thing". Thus, I think it would be preferred for history box changes to be on separate branches. Since there is one parent issue for them, it could be argued that they could be grouped together. You should ask @LeonMontealegre about this.

2022-04-05 21:31 UTC, TGCrystal requested changes
Code looks good, but this is still not working on mobile (iOS) for me. Trying to drag/resize the box does nothing. Absolutely loving it on computer though, this is such a neat feature!

2022-04-11 22:59 UTC, TGCrystal requested changes
Looks like it works on mobile, just one last little nitpick. As shown in the screenshot below, when the History box opens on mobile, it appears horizontally offset (and partially offscreen). I think this is due to the horizontal placement offset that would occur if the history box is first opened when the itemnav is on the left. There should be a small check of some sort so that this horizontal offset is not applied when the itemnav is on the bottom.

![image](https://user-images.githubusercontent.com/29614966/162846795-667f44e0-749c-4b2a-8bda-a28f984cf87f.png)

2022-06-17 17:46 UTC, LeonMontealegre submitted a review, later dismissed

2022-06-17 19:57 UTC, TGCrystal approved these changes

2022-06-19 02:13 UTC, merged