Custom names group actions
OpenCircuits/OpenCircuits pull request #1017
Opened 2022-02-27 21:42 UTC by jssunray34

I added a customName variable and setter method to the GroupActions class to enable GroupActions to be assigned custom names. I also went through the codebase and gave custom names to several existing GroupActions.

Fixes #974

2022-02-27 23:25 UTC, TGCrystal requested changes
Looking good! There are a few more `GroupAction`s that can be named:
- in the `src/app/core/tools/handlers` folder, they can just have names that are the same as the file name (example: the `GroupAction` in `CopyHandler.ts` could be named `Copy Handler`)
- in https://github.com/OpenCircuits/OpenCircuits/blob/master/src/site/pages/digital/src/containers/ExprToCircuitPopup/generate.ts#L112 that group action can be called `Expression Parser Action`
- https://github.com/OpenCircuits/OpenCircuits/blob/master/src/site/pages/digital/src/containers/ICDesigner/index.tsx#L169 can be named `Create IC Action`
- Modules in `src/site/pages/digital/src/containers/SelectionPopup/modules` can be named to match the file name, such as `SelectPortCountModule.tsx` can have its `GroupAction` named `Select Port Count Module`
- https://github.com/OpenCircuits/OpenCircuits/blob/master/src/site/pages/digital/src/utils/DigitalCreate.ts#L98 can be named `Smart Place Group`
- https://github.com/OpenCircuits/OpenCircuits/blob/master/src/site/pages/digital/src/utils/DigitalCreate.ts#L125 can be named `Smart Place` (don't worry about the `GroupAction`s inside of that
- https://github.com/OpenCircuits/OpenCircuits/blob/master/src/site/pages/digital/src/utils/DigitalPaste.ts#L53 can be `Recursive Transfer ICData Action`
- https://github.com/OpenCircuits/OpenCircuits/blob/master/src/site/pages/digital/src/utils/DigitalPaste.ts#L88 can be `Digital Paste`
- https://github.com/OpenCircuits/OpenCircuits/blob/master/src/site/shared/containers/ContextMenu/index.tsx#L77 can be `Cut (Context Menu)`
- https://github.com/OpenCircuits/OpenCircuits/blob/master/src/site/shared/containers/ContextMenu/index.tsx#L77 can be `Title Module`

2022-02-27 23:25 UTC, TGCrystal commented on src/site/pages/digital/src/containers/SelectionPopup/modules/OscilloscopeModules.tsx
> +    getAction: (s, newNumSamples) => new GroupAction(s.map(o => new OscilloscopeSamplesChangeAction(o, newNumSamples)), "Oscilloscope Action")
rename to `"Oscilloscope Samples Change Module"`

2022-02-27 23:25 UTC, TGCrystal commented on src/site/pages/digital/src/containers/SelectionPopup/modules/OscilloscopeModules.tsx
> +        new GroupAction(s.map(o => new InputPortChangeAction(o, o.getInputPortCount().getValue(),  newCount)), "Oscilloscope Action")
rename to `"Oscilloscope Input Count Change Module"`

2022-02-27 23:25 UTC, TGCrystal commented on src/site/pages/digital/src/containers/SelectionPopup/modules/OscilloscopeModules.tsx
> +        new GroupAction(s.map(o => new OscilloscopeSizeChangeAction(o, V(newW, o.getDisplaySize().y))), "Oscilloscope Action")
rename to `"Oscilloscope Width Change Module"`

2022-02-27 23:25 UTC, TGCrystal commented on src/site/pages/digital/src/containers/SelectionPopup/modules/OscilloscopeModules.tsx
> +        new GroupAction(s.map(o => new OscilloscopeSizeChangeAction(o, V(o.getDisplaySize().x, newH))), "Oscilloscope Action")
rename to `"Oscilloscope Height Change Module"`

2022-03-04 22:04 UTC, jssunray34 commented
In your first comment, is the link for `Title Module` supposed to be something else? I think you may have copy-pasted the same link from the above bullet.

2022-03-04 22:07 UTC, TGCrystal commented
> In your first comment, is the link for `Title Module` supposed to be something else? I think you may have copy-pasted the same link from the above bullet.

You are right, here is the correct link: https://github.com/OpenCircuits/OpenCircuits/blob/master/src/site/shared/containers/SelectionPopup/modules/TitleModule.tsx#L11

2022-03-06 03:44 UTC, TGCrystal submitted a review, later dismissed

2022-03-18 17:11 UTC, LeonMontealegre approved these changes
I think a lot of these names could probably be improved to read better to the user, since something like "Selection Box Tool" doesn't sound great, but we can make a separate issue for that and let have it be a "good first issue"

2022-03-18 18:33 UTC, merged