Fixed Wire Delete for issue 902
OpenCircuits/OpenCircuits pull request #1022
Opened 2022-03-02 08:15 UTC by vhada7

Added a boolean variable into the getPath function so that when one or more wires are deleted it only deletes the wires that are connected to those wires instead of all the wires. I also added this to the component function so that if a WirePort is deleted it doesn't delete everything.

2022-03-12 02:54 UTC, TGCrystal requested changes

2022-03-12 02:54 UTC, TGCrystal commented on src/app/core/utils/ComponentUtils.ts
> +
nit: remove added indentation

2022-03-12 02:54 UTC, TGCrystal commented on src/app/core/utils/ComponentUtils.ts
>   * @return   The array of wires/WirePorts in this path (including w)
Please add a short description of the `full` parameter to these javadoc comments

2022-03-12 02:54 UTC, TGCrystal commented on src/app/core/utils/ComponentUtils.ts
>   * @return         A SeparatedComponentCollection of the objects
Please add a short description of the `full` parameter to these javadoc comments

2022-03-12 02:54 UTC, TGCrystal commented on src/app/core/tools/handlers/DeleteHandler.ts
> +        console.log(selectedWires);
nit: remove this `console.log`

2022-03-18 17:43 UTC, LeonMontealegre commented
Note that this now has an issue if you delete both of the endpoints of the wire-tree:
<img width="808" alt="Screen Shot 2022-03-18 at 1 42 50 PM" src="https://user-images.githubusercontent.com/29997057/159055522-bdd8b269-f889-446d-8a72-6df43cba379e.png">
Deleting leads to:
<img width="732" alt="Screen Shot 2022-03-18 at 1 42 58 PM" src="https://user-images.githubusercontent.com/29997057/159055552-a9a9d3ea-72b5-4207-995a-9ac87b61f826.png">

I would **expect** this:
<img width="737" alt="Screen Shot 2022-03-18 at 1 43 05 PM" src="https://user-images.githubusercontent.com/29997057/159055566-8dcefd8c-ef3c-4e7e-a669-e2548673361b.png">

Similarly, this happens if you delete all of the LEDs, it leaves a single node point

2022-06-17 22:44 UTC, LeonMontealegre approved these changes

2022-06-18 02:46 UTC, TGCrystal approved these changes

2022-06-19 02:13 UTC, merged