Allows selections of multiple types of gate to change input size
OpenCircuits/OpenCircuits pull request #1042
Opened 2022-04-05 20:21 UTC by shadowluigi27

I changed the input module from specifying each type of gate, which only allowed selection of gates and their not version to be able to change input (EX: OR and NOR) but not 2 different types of gates (OR and AND). 

By generalizing the type to 'Gate', a selection of  only gates no matter the type are now allowed to change inputs when selected together.

Old Behavior
![image](https://user-images.githubusercontent.com/72285616/161841277-29107ee1-24e6-4f64-8bbf-b19c33ac3b6a.png)

New Behavior
![image](https://user-images.githubusercontent.com/72285616/161841327-4f51b33a-b112-4688-9292-d781439f69ef.png)

Fixes #820

2022-04-05 21:41 UTC, TGCrystal requested changes
`Gate` includes both `Buffer` and `Not`, which do not support changing the input number count. Instead of generalizing to `Gate`, you can do `ANDGate | ORGate | XORGate` (I think that would automatically take care of the inverted versions of those).

2022-04-05 21:41 UTC, TGCrystal commented on src/site/pages/digital/src/containers/SelectionPopup/modules/InputCountModule.tsx
> +
nit: only two spaces between last import and start of code, so this empty line is unnecessary

2022-04-13 21:17 UTC, TGCrystal requested changes

2022-04-13 21:17 UTC, TGCrystal commented on src/site/pages/digital/src/containers/SelectionPopup/modules/InputCountModule.tsx
> +
This still needs to be addressed, but looks good otherwise

2022-04-15 21:37 UTC, TGCrystal approved these changes

2022-04-18 23:09 UTC, LeonMontealegre requested changes
Looking good, just a few formatting issues!

2022-04-18 23:09 UTC, LeonMontealegre commented on src/site/shared/containers/SelectionPopup/modules/Module.tsx
> +        {for (let exclusion of config.exclude)  { if(s instanceof exclusion) {return false;}}}
I think this can be condensed down to 
```ts
if (config.exclude?.some(exclusion => s instanceof exclusion))
    return false;
```

2022-04-18 23:09 UTC, LeonMontealegre commented on src/site/shared/containers/SelectionPopup/modules/Module.tsx
> +        // check if s instanceof Type and also not instnace of anything in config.exclude
nit: capitalize first letter of comment, also typo on `instance`, also mention this was necessary for issue #820

2022-05-13 09:48 UTC, LeonMontealegre approved these changes

2022-05-13 10:03 UTC, merged