Preview objects that are Dragged and dropped in the navbar to be deleted
OpenCircuits/OpenCircuits pull request #1047
Opened 2022-04-15 21:36 UTC by alstar555

Added a preview for objects that are dragged and dropped into the navigation bar to be deleted
![fixedIssueNavPreview](https://user-images.githubusercontent.com/67800009/163635016-619e2ba6-eeec-4ecf-ac0e-dd21e11c322b.gif)
.

2022-04-15 21:51 UTC, TGCrystal requested changes
Functionality looks good to me. It doesn't work on mobile, but neither does dragging to the itemnav to delete at all. Fixing that would probably be outside the scope of this pr, so you don't have to worry about it.

There is probably some way that the general logic should be refactored instead of relying on a large nested function. I'm not sure what exactly that is, so you should consult @LeonMontealegre on that.

2022-04-15 21:51 UTC, TGCrystal commented on src/site/shared/containers/ItemNav/index.tsx
> +    //track whether mouse is over Nav bar
nit: add space after `//`

2022-04-15 21:51 UTC, TGCrystal commented on src/site/shared/containers/ItemNav/index.tsx
> +        var item_icon;
nit: use `let` instead of `var`

2022-04-15 21:51 UTC, TGCrystal commented on src/site/shared/containers/ItemNav/index.tsx
> +        if(!overNav){
nit: add space between `if` and `(`

2022-04-15 21:51 UTC, TGCrystal commented on src/site/shared/containers/ItemNav/index.tsx
> +                }}>
Not sure if linting said to change this spacing, but if it didn't then it should be what it was before

2022-05-13 07:14 UTC, LeonMontealegre submitted a review, later dismissed

2022-05-13 10:11 UTC, merged