More linting fixes
OpenCircuits/OpenCircuits pull request #1091
Opened 2022-07-23 00:31 UTC by TGCrystal

Fixes on of the checkboxes on #1088 
Also enforces some spacing around keywords and inside parenthesis

2022-09-01 03:58 UTC, LeonMontealegre reviewed
A lot of the problems are with vertical align, but idk how we're gonna fix that.
Would almost certainly require a custom plugin that allows spaces in parenthesis if it detects some sort of vertical alignment but detecting that sounds complicated but im not entirely sure what to do in the meantime

we'll have to discuss further

2022-09-01 03:58 UTC, LeonMontealegre commented on src/app/analog/models/eeobjects/sources/VoltageSource.ts
> +           ...TimeInfo("p", "Period",       0.2),
The vertical align is messed up here

2022-09-01 03:58 UTC, LeonMontealegre commented on src/app/core/actions/selection/SelectAction.ts
> +                                   new GroupAction([], "Deselect All Action"));
preferably:
```ts
return objs.reduce(
    (acc, s) => acc.add(new DeselectAction(selections, s)),
    new GroupAction([], "Deselect All Action")
);
```

2022-09-01 03:58 UTC, LeonMontealegre commented on src/app/core/rendering/CreateRenderers.ts
> +) => {return {
?

2022-09-01 03:58 UTC, LeonMontealegre commented on src/app/core/rendering/renderers/IOLabelRenderer.ts
> +        const max = V(xBound,  yBound);
vertical align :(

2022-09-01 03:58 UTC, LeonMontealegre commented on src/app/core/tools/handlers/PasteHandler.ts
> +export const PasteHandler = (paste: (text: string) => boolean): EventHandler => ({
need to de-indent the following lines

2022-09-01 03:58 UTC, LeonMontealegre commented on src/app/core/tools/handlers/PasteHandler.ts
> +    })
semi-colon at end

2022-09-01 03:58 UTC, LeonMontealegre commented on src/app/core/tools/handlers/SaveHandler.ts
> +export const SaveHandler = (save: () => void): EventHandler => ({
need to de-indent the following lines

2022-09-01 03:58 UTC, LeonMontealegre commented on src/app/core/utils/Input.ts
> +                       keys.some((key) => this.isKeyDown(key))));
spacing is weird here

2022-09-01 03:58 UTC, LeonMontealegre commented on src/app/core/utils/math/Rect.ts
> +        ].filter((r) => r.width > 0 && r.height > 0);
,parenthesis around the filter body, i think the rule of thumb is that if you have a statement that contains a space, i.e. a comparision like ` == ` or ` > ` or ` && ` or something, there should be parenthesis

2022-09-01 03:58 UTC, LeonMontealegre commented on src/app/digital/actions/addition/BusActionFactory.ts
> +    const inputMap  = new Map(inputAngles.map((a, i) => [a,  inputPorts[i]]));
vertical align :(

2022-09-01 03:58 UTC, LeonMontealegre commented on src/app/digital/models/ioobjects/other/ICData.ts
> +        const others  = copies.getComponents().filter((c) => (!inputs.includes(c) && !outputs.includes(c)));
vertical align :(

2022-09-01 03:58 UTC, LeonMontealegre commented on src/app/digital/utils/ComponentUtils.ts
> +    const checkInUse = (objs: IOObject[]): boolean => objs.some((o) =>
spacing is weird here

2022-09-01 03:58 UTC, LeonMontealegre commented on src/app/digital/utils/DigitalVersionConflictResolver.ts
> +                                                            }) => [newKey, (data[prevKey] ?? defaultVal)])),
spacing is weird

2022-09-01 03:58 UTC, LeonMontealegre commented on src/app/tests/digital/utils/actions/BusAction.test.ts
> +        o1.setPos(V(100, 0));
vertical align :( (on entire file)

2022-09-01 03:58 UTC, LeonMontealegre commented on src/app/tests/digital/utils/math/Matrix.test.ts
> +                expect(m["mat"][0]).toBeCloseTo(0, 1e-3);
vertical align :(

2022-09-01 03:58 UTC, LeonMontealegre commented on src/app/tests/digital/utils/math/Transform.test.ts
> +                expect(t.toLocalSpace(V(5, -5))).toApproximatelyEqual(V(0, 0));
vertical align :(

2022-09-01 03:58 UTC, LeonMontealegre commented on src/site/pages/analog/src/containers/AnalogItemNav/index.tsx
> +        const item = section?.items.find((i) => i.id === id);
parenthesis on inner .find body

2022-09-01 03:58 UTC, LeonMontealegre commented on src/site/pages/analog/src/utils/hooks/useAnalog.ts
> +export const useAnalogDispatch = () => useDispatch<ThunkDispatch<AppState, undefined, AllActions>>()
semi-colon at end

2022-09-01 03:58 UTC, LeonMontealegre commented on src/site/pages/digital/src/containers/DigitalItemNav/index.tsx
> +        const item = section?.items.find((i) => i.id === id);
parenthesis in inside body

2022-09-01 03:58 UTC, LeonMontealegre commented on src/site/pages/digital/src/utils/hooks/useDigital.ts
> +export const useDigitalDispatch = () => useDispatch<ThunkDispatch<AppState, undefined, AllActions>>()
semicolon at end

2022-09-01 03:58 UTC, LeonMontealegre commented on src/site/shared/containers/HistoryBox/index.tsx
> +                                                                         isRedo={isRedo} />))}
spacing is weird

2022-09-01 03:58 UTC, LeonMontealegre commented on src/site/shared/containers/ItemNav/index.tsx
> +        return config.sections.reduce((prev, section) => [
need to de-indent body

2022-09-01 03:58 UTC, LeonMontealegre commented on src/site/shared/utils/hooks/useShared.ts
> +export const useSharedDispatch = () => useDispatch<ThunkDispatch<SharedAppState, undefined, AllSharedActions>>()
semi-colon

2022-09-02 16:53 UTC, TGCrystal commented on src/app/core/utils/Input.ts
> +                       keys.some((key) => this.isKeyDown(key))));
What spacing do you want here?

2022-09-02 17:18 UTC, LeonMontealegre commented on src/app/core/utils/Input.ts
> +                       keys.some((key) => this.isKeyDown(key))));
probably something like:
```ts
return PREVENTED_COMBINATIONS.some((combination) => (
    combination.flat().includes(newKey) &&
    combination.every((keys) => (
        keys.some((key) => this.isKeyDown(key))
    )
));
```

2022-09-03 17:46 UTC, LeonMontealegre requested changes
only a few more spacing issues

2022-09-03 17:46 UTC, LeonMontealegre commented on src/app/digital/rendering/ioobjects/outputs/LEDRenderer.ts
> +
Where'd the comment go?

2022-09-03 17:46 UTC, LeonMontealegre commented on src/app/digital/utils/ComponentUtils.ts
> +    const checkInUse = (objs: IOObject[]): boolean => objs.some((o) =>
should be like:
```ts
const checkInUse = (objs: IOObject[]): boolean => objs.some((o) => (
    o instanceof IC &&
    (o.getData() === data ||
        // Recursively check if this IC depends on the given data
        checkInUse(o.getData().getGroup().toList()))
));
```

2022-09-03 17:46 UTC, LeonMontealegre commented on src/app/core/actions/selection/SelectAction.ts
> +        new GroupAction([], "Deselect All Action"));
put the last `);` on the next line

2022-09-03 17:46 UTC, LeonMontealegre commented on src/app/digital/utils/DigitalVersionConflictResolver.ts
> +                    [newKey, (data[prevKey] ?? defaultVal)])),
should be:
```ts
data: Object.fromEntries(
    transformation.map(({ prevKey, newKey, defaultVal }) => 
        [newKey, (data[prevKey] ?? defaultVal)]
    )
)

2022-09-03 17:46 UTC, LeonMontealegre commented on src/site/shared/containers/HistoryBox/index.tsx
> +                               isRedo={isRedo} />))}
i think something more like:
```ts
{!isCollapsed && g.getActions().map((a, i) => (
    <HistoryEntry key={`group-action-entry-${i}`}
                  a={a}
                  isRedo={isRedo} />
))}
```

2022-09-04 17:40 UTC, LeonMontealegre approved these changes

2022-09-06 19:41 UTC, LeonMontealegre approved these changes

2022-09-06 19:42 UTC, merged