Add back inductor
OpenCircuits/OpenCircuits pull request #1183
Opened 2022-10-18 20:58 UTC by padauker

#1168

2022-10-25 00:53 UTC, TGCrystal submitted a review, later dismissed

2022-11-03 02:02 UTC, TGCrystal approved these changes

2022-11-08 18:34 UTC, LeonMontealegre requested changes
Looking good! Just a few nits and recommendations!

2022-11-08 18:34 UTC, LeonMontealegre commented on src/app/analog/views/index.ts
> +
Keep these vertically aligned at `(c, o)`

2022-11-08 18:34 UTC, LeonMontealegre commented on src/app/core/models/types/analog.ts
> +    "CurrentSource": (id) => ({ ...DefaultComponent(id), kind: "CurrentSource", amperage: 1 }),
keep these all vertically aligned at
`(id) =>`
and similarly, keep the end of the lines vertically aligned with the `}),`

2022-11-08 18:34 UTC, LeonMontealegre commented on src/app/core/views/portinfo/analog/index.ts
> +                { origin: V(0, +0.925), target: V(0, +1.425), dir: V(0, +1) },
these values should probably be more explicit as they depend on the height of the inductor which we know is `240*0.8/104` (which comes from the size of the `inductor.svg` image btw), so like the origin y should be like `240/104*0.8/2`, you can (and probably should) even just store a constant at the top of this file called `INDUCTOR_HEIGHT` which is set to `240/104*0.8`

2022-11-08 18:34 UTC, LeonMontealegre commented on src/app/core/views/portinfo/analog/index.ts
> +        }],
If you want to go above and beyond here, you could create a utility method in `app/core/views/portinfo/positioning/utils.ts` called like `TwoPortPositioner` which would be like:
```ts
export function TwoPortPositioner(dir: "horizontal" | "vertical", size: number): PortConfig[]
```
which would be used like
```ts
"Resistor": {
    ...
    PositionConfigs: [{ "ports": TwoPortPositioner("horizontal", 1.2) }],
}
...
"Inductor": {
    ...
    PositionConfigs: [{ "ports": TwoPortPositioner("vertical", 240/104*0.8) }],     
},
...
"CurrentSource": {
    ...
    PositionConfigs: [{ "ports": TwoPortPositioner("vertical", 1) }],
},
...
```

2023-01-25 00:04 UTC, closed without merging