Model refactor nand
OpenCircuits/OpenCircuits pull request #1192
Opened 2022-10-25 21:16 UTC by aruan20

2022-11-03 03:01 UTC, TGCrystal reviewed
The logic doesn't seem to work when using more than one import port, but it is hard to consistently test since the selection popup is kind of broken (not your fault). Otherwise, looks good to me so far though

2022-11-08 19:27 UTC, LeonMontealegre requested changes
Looking good! Just a few things to fix

2022-11-08 19:27 UTC, LeonMontealegre commented on src/app/digital/views/DigitalPortView.ts
> +        renderer.draw(new Circle(target, IO_PORT_RADIUS), circleStyle);
use `super.renderInternal` for all of this

2022-11-08 19:27 UTC, LeonMontealegre commented on src/app/digital/views/DigitalPortView.ts
> +        if (this.circuit.getPortParent(this.obj).kind === "NANDGate" && this.obj.group === "outputs"){
make a constant right above called `parent = this.circuit.getPortParent(this.obj)` to simplify this a bit
Also add a comment explaining why this is necessary for now

2022-11-08 19:27 UTC, LeonMontealegre commented on src/app/digital/views/components/NANDGateView.ts
> +export class NANDGateView extends ComponentView<NANDGate, DigitalViewInfo> {
Notice how similar this is to `ANDGateView`, we probably want to re-use `ANDGateView`, so to do this, we can have `ANDGateView` extend `ComponentView<ANDGate | NANDGate` and take in an `ANDGate | NANDGate` and then re-use this in `src/app/digital/views/index.ts`

2022-11-18 19:58 UTC, LeonMontealegre approved these changes

2023-01-25 00:04 UTC, closed without merging