OrGate added back
OpenCircuits/OpenCircuits pull request #1200
Opened 2022-11-02 21:14 UTC by Kagiri2

2022-11-03 03:20 UTC, TGCrystal requested changes
2 issues I noticed:
1) The gates themselves are using the logic for AND gates rather than xor/xnor
2) The XNOR has the port behind the line. Whoever implemented the NANDGate in #1192 ran into this, Leon's solution was: "I think the solution here might be to draw the circle in DigitalPortView, so the port will draw its circle (override renderInternal, see PortView).
For it to know if it should draw the circle or not, you can get the parent component from the Port and just check if it's kind is a NANDGate and that the Port itself is an Output port and we'll eventually make a better system; but for now this is fine"

2022-11-08 19:47 UTC, LeonMontealegre requested changes
Looking good! Just a few things to do

2022-11-08 19:47 UTC, LeonMontealegre commented on src/app/core/views/portinfo/digital/index.ts
> +import {CalcPortPos, CalcPortPositions,CalcQuadCurvePortPositions} from "../positioning/utils";
nit: put space after `,`

2022-11-08 19:47 UTC, LeonMontealegre commented on src/app/core/views/portinfo/digital/index.ts
> +            "outputs": [CalcPortPos(V(0.8, 0), V(.7, 0))], // 1 output
I think the outputs here can be the same as `ORGate`, the circle for the not can simply lay on-top of the port
![Screen Shot 2022-11-08 at 2 36 31 PM](https://user-images.githubusercontent.com/29997057/200658745-3a0c1663-16db-4711-b37f-29339a5179ab.png)
(this is a screenshot from master)

2022-11-08 19:47 UTC, LeonMontealegre commented on src/app/digital/views/components/NORGateView.ts
> +// // sheesh
??

2022-11-08 19:47 UTC, LeonMontealegre commented on src/app/digital/views/index.ts
> +import { NORGateView } from "./components/NORGateView";
remove spaces and sort imports

2022-11-08 19:47 UTC, LeonMontealegre commented on src/app/digital/views/info/index.ts
> +    "ORGate": DefaultComponentPropInfo,
vertically align

2023-01-25 00:03 UTC, closed without merging