Fleshed out CircuitInternal
OpenCircuits/OpenCircuits pull request #1217
Opened 2023-01-30 06:48 UTC by KevinMackenzie

- preliminary `applyOps` impl
- more front-end functions
- more flexible transactions
- `CircuitLog` proto-OT logic
- Low-level event propagation
- expanded "Info" types.

Please ignore the egregiously inconsistent Error strings for now.

2023-01-30 16:32 UTC, KevinMackenzie commented on src/app/core/internal/impl/CircuitInternal.ts
> +        this.endTransactionHelper(() => {});
Whoops.  This needs to revert the `transactionOps`

2023-01-30 16:54 UTC, KevinMackenzie commented on src/app/core/internal/impl/CircuitInternal.ts
> +        this.applyOp(op);
Cancel the transaction if `applyOp` throws an exception here

2023-01-30 19:39 UTC, LeonMontealegre requested changes

2023-01-31 01:51 UTC, KevinMackenzie commented on src/app/core/internal/impl/CircuitOps.ts
> +    // Components are born without ports
It helps reduce the complexity of the individual ops and doesn't introduce any problematic intermediary states.  I'll add a comment to that effect.

2023-01-31 01:52 UTC, KevinMackenzie commented on src/app/core/internal/impl/CircuitInternal.ts
> +    public setPropForDyn(id: GUID, key: string, newVal?: Schema.Prop): void {
Short for "Dynamic".  Will make name more clear.

2023-01-31 01:52 UTC, KevinMackenzie commented on src/app/core/public/api/impl/Component.ts
> +        return [...this.circuit.getPortsForComponent(this.id)]
`Set` doesn't have a `.map`.

2023-01-31 03:06 UTC, LeonMontealegre approved these changes

2023-01-31 03:06 UTC, merged