Implement connectWire method in DigitalCircuit
OpenCircuits/OpenCircuits pull request #1229
Opened 2023-02-11 03:26 UTC by huynchu

Implemented the `connectWire()` method + 2 unit test to test connecting a wire between two different ports and connecting a wire to the same port.

2023-02-11 23:28 UTC, LeonMontealegre requested changes

2023-02-11 23:28 UTC, LeonMontealegre commented on src/app/tests/ConnectWire.test.ts
> +        }
We know it's not undefined, and if it is then we have other problems

You can do `wire!.p1` to assert that it's not undefined

2023-02-15 02:23 UTC, huynchu commented
Hopefully, all the issues are fixed through the commits I made today!

2023-02-17 21:01 UTC, LeonMontealegre requested changes

2023-02-17 21:01 UTC, LeonMontealegre commented on src/app/tests/ConnectWire.test.ts
> +      expect(p1).toBe(p2);
We don't really need to test to see if the ports are the same here, it's pretty clear, you can just do `expect(circuit.connectWire(c.ports[0], c.ports[0])).toBeUndefined()`

2023-02-17 21:01 UTC, LeonMontealegre commented on src/app/digital/public/api/impl/DigitalCircuit.ts
> +
nit: remove extra spaces

2023-02-18 03:30 UTC, LeonMontealegre requested changes
almost there! just a few nits!

2023-02-18 03:30 UTC, LeonMontealegre commented on src/app/tests/ConnectWire.test.ts
> +      expect(circuit.connectWire(c.ports[0], c.ports[0])).toBeUndefined()
nit: semicolon

2023-02-18 03:30 UTC, LeonMontealegre commented on src/app/core/internal/impl/CircuitInternal.ts
> +                if (op.w.p1 == op.w.p2)
nit: use `===`

2023-02-18 03:30 UTC, LeonMontealegre commented on src/app/tests/ConnectWire.test.ts
> +describe("connectWire", () => {
nit: capitalize, like `ConnectWire`

2023-02-18 03:30 UTC, LeonMontealegre commented on src/app/tests/ConnectWire.test.ts
> +        const l1 = circuit.placeComponentAt(V(5,   0), "LED");
nit: spacing in the `V`

2023-03-05 18:22 UTC, LeonMontealegre commented
Make sure to update your branch and resolve the conflicts!

Note that we merged the new "error" system for `CircuitInternal`, so there will now be a less-gross way to catch any errors from `.connectWire` instead of `try-catch`ing

2023-03-27 23:52 UTC, LeonMontealegre commented
Your PR diff is massive right now, I think you need to update your branch again?

2023-04-13 20:51 UTC, LeonMontealegre requested changes

2023-04-13 20:51 UTC, LeonMontealegre commented on src/app/core/internal/impl/CircuitInternal.ts
> +          this.objStorage.set(op.c.id, op.c);
it's not compiling because this statement is floating in the middle of nowhere haha

2023-04-13 20:51 UTC, LeonMontealegre commented on src/app/digital/public/api/impl/DigitalCircuit.ts
>          //         in that case
please remove the comment now that you've implemented everything

2023-04-13 20:51 UTC, LeonMontealegre commented on src/app/digital/public/api/impl/DigitalCircuit.ts
> +            return wire.ok ? wire.value : undefined;
nit: please de-indent

2023-04-13 20:51 UTC, LeonMontealegre commented on src/app/tests/ConnectWire.test.ts
> +  });
add a test case for:
- trying to connect an output port to another output port
- trying to connect an input port to another input port
- trying to connect to input port that already has a connection
- connecting to an output port that already has a connection (should succeed)

2023-04-13 20:51 UTC, LeonMontealegre commented on src/app/tests/ConnectWire.test.ts
> +        expect(l1.pos).toEqual(V(5, 0));
you don't need to test that the positions are correct, we're just testing `connectWire` here

2023-04-13 20:51 UTC, LeonMontealegre commented on src/app/tests/ConnectWire.test.ts
> +        const wire = circuit.connectWire(p1,p2);
nit: missing space after `,`

2023-04-13 20:51 UTC, LeonMontealegre commented on src/app/tests/ConnectWire.test.ts
> +describe("ConnectWire", () => {
fix indentation in this whole `describe`

2023-05-05 21:05 UTC, closed without merging