Added Shortcuts to Analog
OpenCircuits/OpenCircuits pull request #1236
Opened 2023-03-21 20:28 UTC by julianchen215

We have succesfully added keyboard shortcuts to the Analog version of OpenCircuits:
“V” for voltage source
“G” for ground
“R” for Resistor
“C” for capacitor
“L” for inductor
“I” for current source

2023-03-22 03:33 UTC, LeonMontealegre requested changes
Just a quick change for now, will make a more thorough review later once you've fixed all of the linting errors (which you should please do)

2023-03-22 03:33 UTC, LeonMontealegre commented on src/site/shared/containers/ItemNav/index.tsx
> +        for (var short of shortcuts){
Never use var, use `let` or `const`, (`const` here)

2023-03-23 01:11 UTC, TGCrystal commented on src/site/shared/containers/ItemNav/index.tsx
> +            if (ev.key === short[0]){
Add space between `)` and `{`

2023-03-23 01:55 UTC, TGCrystal requested changes
Functionality wise, I think pressing the same shortcut for whatever item is currently selected (like if you press `s` after you already did once to select Switch) then it should unselect it just like right clicking does.

Bugs wise, the only issues I found relate to dragging an item from the item nav while a shortcut is being used
1. Open itemnav
2. Press s
3. right click
4. Click Segment Display
5. Click canvas to place Segment Display

It still tries to display a preview to place (it shouldn't), and it isn't finding an image to preview so it displays the alt placeholder text. Strangely enough, it does find a preview if you use Clock instead of Segment Display, although it still shouldn't have a preview.

A similar issue happens when:
1. Open itemnav
2. Press s
3. Drag an Segment Display onto the itemnav

The preview is still there (and still fails to display).

Aside from that and the fixes proposed by the linter and Leon, this looks good! I do like this new functionality quite a bit, it feels much more ergonomic and useful than I expected.

2023-03-23 01:55 UTC, TGCrystal commented on src/site/shared/containers/ItemNav/index.tsx
> +        if(shortcut_flag){
```suggestion
        if (shortcut_flag) {
```

2025-06-30 03:27 UTC, closed without merging