Re-add all Tool Handlers
OpenCircuits/OpenCircuits pull request #1254
Opened 2023-04-17 05:43 UTC by LeonMontealegre

Also add `Node` API type.

Most handlers are still non-functional, but they all depend on API methods that need to be implemented.

2023-04-24 23:58 UTC, TGCrystal requested changes

2023-04-24 23:58 UTC, TGCrystal commented on src/app/core/public/api/impl/Selections.ts
> +    }
I think this would look better with the `.filter` on its own line like the `forEach` function below

2023-04-24 23:58 UTC, TGCrystal commented on src/site/shared/circuitdesigner/impl/CircuitDesigner.ts
> +             })));
Can the last `));` be moved to the next line so it is a little clearer what they are closing?

2023-04-25 11:27 UTC, TGCrystal approved these changes

2023-05-06 23:07 UTC, KevinMackenzie approved these changes
No major issues (or any that I remember)

2023-05-07 00:36 UTC, merged