Wire double click fix
OpenCircuits/OpenCircuits pull request #593
Opened 2021-02-26 21:03 UTC by JumpingKangaroo

Closes issue #521 

Allows users to click through a SelectionPopup for 500ms after it is shown. After that point, it becomes clickable. This will let the user double click a wire to select all connected wires, even if the wires are in a configuration where normally the box popup would block the wire.

I tested this out with the fix to wire selection that was just merged to master and was able to double click through it for half a second.

2021-03-13 00:29 UTC, Xystem4 commented
Seems to properly take care of the issue. Works regardless of what portion of the popup box is obstructing the mouse (you can control this by zooming in until the wire takes the entire screen).

One note that is that the double clicking works even if something else is obstructing the wire (a node, a gate, another wire, etc.), which may or may not be the desired functionality. I believe this is not a result of these changes however, but has been present since the double-click functionality was added.

2021-03-13 00:55 UTC, Xystem4 approved these changes

2021-03-13 01:33 UTC, LeonMontealegre requested changes

2021-03-13 01:33 UTC, LeonMontealegre commented on src/site/shared/containers/SelectionPopup/index.tsx
> +                setTimeout(() => setState((prevState) =>
Let's write this as:
```
setTimeout(() => 
    setState((prevState) => ({ ...prevState, clickThrough })),
    DOUBLE_CLICK_DURATION
);
```

2021-03-16 20:32 UTC, JumpingKangaroo commented
@LeonMontealegre Whenever you get a chance, made the changes you recommended above!

2021-03-16 22:03 UTC, LeonMontealegre approved these changes

2021-03-16 22:06 UTC, merged