Example circuit fix
OpenCircuits/OpenCircuits pull request #619
Opened 2021-03-23 20:23 UTC by JumpingKangaroo

This fixes #599. It attaches a callback to every time an example circuit is requested, that runs the circuit through the `VersionConflictResolver`. If the version is up to date, then `VersionConflictResolver` is a no op. 

I'm able to load into the example circuits as normal, edit them, and then save them to my personal save collection.

2021-03-23 23:12 UTC, LeonMontealegre requested changes
Great job! But I think in part we should actually update the example circuits to be the most recent version, could you update them as part of this PR? You just gotta load them and save them using the Download file functionality and then replace the file in `examples`

2021-03-23 23:12 UTC, LeonMontealegre commented on src/site/shared/containers/SideNav/index.tsx
> +    );
This can be compressed down to just `.then(VersionConflictResolver)`

2021-03-26 21:11 UTC, JumpingKangaroo commented
Made the changes! To test that the example circuits were updated correctly, I commented out the `.then(VersionConflictResolver)` and then verified that I could open the example circuits.

2021-04-02 18:05 UTC, LeonMontealegre approved these changes

2021-04-02 18:05 UTC, merged