Allow ICs to be deleted from ItemNav
OpenCircuits/OpenCircuits pull request #793
Opened 2021-10-18 20:33 UTC by Cyphecx

Addresses issue #723.

I created an undoable action that will remove an IC from the item nav as long as there are no remaining instances of that IC in the circuit.

https://user-images.githubusercontent.com/20589728/137802479-b98f413d-c3ce-4e7b-b392-7c25d2bb28dd.mp4

The delete button is just a capital red X. It fits fairly well with the rest of the site's design but we might want to change it at somepoint.

![image](https://user-images.githubusercontent.com/20589728/137798895-6ae84ec5-f2d3-4b11-b7cc-1008726ddd17.png)

2021-11-05 02:29 UTC, LeonMontealegre requested changes

2021-11-05 02:29 UTC, LeonMontealegre commented on src/app/digital/actions/DeleteICDataAction.ts
> +
nit: need 2 empty lines after imports before first statement

2021-11-05 02:29 UTC, LeonMontealegre commented on src/site/shared/containers/ItemNav/index.scss
> +                        & > div{
nit: space before `{`

2021-11-05 02:29 UTC, LeonMontealegre commented on src/site/shared/containers/ItemNav/index.tsx
> +import {DeleteICDataAction} from '../../../../app/digital/actions/DeleteICDataAction';
nit: use `"` not `'`

nit: these can be shortened to `from "digital/models/......"`

2021-11-05 02:29 UTC, LeonMontealegre commented on src/site/shared/containers/ItemNav/index.tsx
> +
nit: delete extra space

2021-11-05 02:29 UTC, LeonMontealegre commented on src/site/shared/containers/ItemNav/index.tsx
> +    const [hovering, setHover] = useState("")
nit: need semicolon at end

2021-11-05 02:29 UTC, LeonMontealegre commented on src/site/shared/containers/ItemNav/index.tsx
> +import {ICData} from "digital/models/ioobjects";
digital should **never** be imported to shared or core, shared is _shared_ between analog and digital, so when analog uses this, it shouldn't have to know what digital is

2021-11-05 02:29 UTC, LeonMontealegre commented on src/site/shared/containers/ItemNav/index.tsx
> +                                        onMouseEnter={() => {
nit: keep first property on the same line as `<div`

2021-11-05 02:29 UTC, LeonMontealegre commented on src/site/shared/containers/ItemNav/index.tsx
> +
nit: delete extra line

2021-11-05 02:29 UTC, LeonMontealegre commented on src/site/shared/containers/ItemNav/index.tsx
> +
nit: delete extra line

2021-11-05 02:29 UTC, LeonMontealegre commented on src/site/shared/containers/ItemNav/index.tsx
> +    }
So as stated above, shared shouldn't know that digital exists. 
So to fix this, what we can do is have `onDelete` as a function in the `Props` for `ItemNav` and then in `DigitalItemNav` you can pass in `onDelete` as this function

2021-11-05 02:29 UTC, LeonMontealegre commented on src/site/shared/containers/ItemNav/index.tsx
> +                                                deleteIC(section, item);
coupled with the above comment, this would then call `onDelete(section, item)`

2021-11-05 20:03 UTC, LeonMontealegre requested changes

2021-11-07 04:55 UTC, LeonMontealegre requested changes

2021-11-07 04:55 UTC, LeonMontealegre commented on src/site/pages/digital/src/containers/DigitalItemNav/index.tsx
> +            }
nit: Remove `else {}` since the previous `if` statement returns when true

2021-11-07 04:55 UTC, LeonMontealegre commented on src/site/pages/digital/src/containers/DigitalItemNav/index.tsx
> +            const icData = designer.getICData()[icIndex];
nit: Just inline `icIndex` into line 114

2021-11-07 04:55 UTC, LeonMontealegre commented on src/site/shared/containers/ItemNav/index.tsx
nit: Delete extra line

2021-11-07 04:55 UTC, LeonMontealegre commented on src/site/shared/containers/ItemNav/index.tsx
> +                                         }}
Can reduce this to `<div onMouseEnter={() => (item.removable && setHover(item.id))}`
and similarly for `onMouseLeave`

2021-11-07 04:55 UTC, LeonMontealegre commented on src/site/shared/containers/ItemNav/index.tsx
> +                                            }}>X</div>
nit: Tab this all over one more to the right and then put the 
```tsx
}}>
    X
</div>
on the next lines

2021-11-08 23:24 UTC, Cyphecx commented
With the new drag and drop preview I had to add a quick line to stop the preview from sticking around after an IC has been deleted. It is still breifly showing a ghost compnent, but it goes away in about a second or after the delete dialogue is closed. Im not sure if there is a way to prevent the preview from showing when the delete button is pressed, but right now I dont think it is necessary.

2021-11-11 22:49 UTC, LeonMontealegre commented
@OwenMcGee Can you try and break the functionality here? Looks good but I'm skeptical cause also cause of new Drag'N'Drop stuff

2021-11-11 22:51 UTC, LeonMontealegre requested changes

2021-11-11 22:51 UTC, LeonMontealegre commented on src/site/shared/containers/ItemNav/index.tsx
> +                                                </div>
nit: Indent these one to the left

2021-11-11 22:51 UTC, LeonMontealegre commented on src/site/pages/digital/src/containers/DigitalItemNav/index.tsx
> +            const icData = designer.getICData()[+ic.id.substr(ic.id.indexOf('/')+1)];
nit: just do `info.designer` and remove the line above this one

2021-11-16 06:21 UTC, LeonMontealegre approved these changes
Approved! But going to wait on merge until @OwenMcGee attempts to break it

2021-11-16 21:30 UTC, OwenMcGee commented
I don't think this is really an issue but I'll document it anyway, when deleting an IC from the itemNav and then undoing the deletion, it will be placed at the bottom of the list of ICs, not the position it used to be at.

Like @Cyphecx said, there is still the slight visual bug of when you click the red x, it temporarily shows a preview of the IC itself, before it is removed from the itemNav, but I don't know if that's something that's easy to get around.

I still think it would be a good idea to give the user a "would you like to remove all remaining ICs on the canvas?" option in the messagebox that comes up when the user clicks the x with ICs still remaining on the canvas.

Other than those though (which are subjective), this has my stamp of approval!

2021-11-16 21:41 UTC, Cyphecx commented
I personally dont think the mass delete is worthwhile, but I do think we should get this PR merged and then we can make a issue for the feature if its wanted.

2021-11-17 04:02 UTC, OwenMcGee approved these changes
Looks good!

2021-11-17 04:03 UTC, merged