ESC IMPROVEMENT
OpenCircuits/OpenCircuits pull request #854
Opened 2021-11-05 21:44 UTC by BaiTueeChuan

This is ESC improvement. This allows users to use ESC to blur on all kinds of text field.

2021-11-05 21:54 UTC, BaiTueeChuan commented
This is #632

2021-11-08 01:45 UTC, LeonMontealegre commented
I believe you forgot to commit the `InputField` tsx file? It says it's empty

2021-11-12 03:24 UTC, LeonMontealegre requested changes

2021-11-12 03:24 UTC, LeonMontealegre commented on src/site/shared/components/InputField/index.tsx
> +import { useEffect, useRef } from "react"
nit: remove spaces inside braces

2021-11-12 03:24 UTC, LeonMontealegre commented on src/site/shared/components/InputField/index.tsx
> +
nit: remove extra lines

2021-11-12 03:24 UTC, LeonMontealegre commented on src/site/shared/components/InputField/index.tsx
> +
nit: remove extra line, should be exactly 2 empty lines below imports

2021-11-12 03:24 UTC, LeonMontealegre commented on src/site/shared/components/InputField/index.tsx
> +
nit: remove extra line

2021-11-12 03:24 UTC, LeonMontealegre commented on src/site/shared/components/InputField/index.tsx
> +            }
nit: Remove braces since it's a single-line `if`

2021-11-12 03:24 UTC, LeonMontealegre commented on src/site/shared/components/InputField/index.tsx
> +                  {...props} />
nit: move onto same line

2021-11-12 03:24 UTC, LeonMontealegre commented on src/site/pages/digital/src/containers/ICDesigner/index.tsx
> +import { InputField } from "shared/components/InputField";
nit: remove spaces inside braces

2021-11-12 03:24 UTC, LeonMontealegre commented on src/site/shared/containers/Header/Left/index.tsx
> +import { InputField } from "shared/components/InputField";
nit: remove spaces inside braces

2021-11-12 03:24 UTC, LeonMontealegre commented on src/site/shared/containers/Header/Right/OpenFileButton.tsx
> +import { InputField } from "shared/components/InputField";
nit: remove spaces inside braces

2021-11-12 03:24 UTC, LeonMontealegre commented on src/site/shared/containers/Header/Right/OpenFileButton.tsx
> +                                    helpers.LoadCircuit(() => LoadFile(e.target.files[0]))
nit: too many spaces here, should be 4

2021-11-12 03:24 UTC, LeonMontealegre commented on src/site/shared/containers/SelectionPopup/modules/Module.tsx
> +import { InputField } from "shared/components/InputField";
nit: remove spaces inside braces

2021-11-12 21:34 UTC, BaiTueeChuan commented
I've changed code formatting. Is there anything else I still need to change.

2022-01-04 01:26 UTC, LeonMontealegre approved these changes

2022-01-04 01:30 UTC, merged