Add ability to double click to select all connected components
OpenCircuits/OpenCircuits pull request #987
Opened 2022-02-10 17:11 UTC by mercuryhg31

Closes #800

2022-02-24 03:53 UTC, TGCrystal approved these changes

2022-02-24 15:10 UTC, LeonMontealegre requested changes

2022-02-24 15:10 UTC, LeonMontealegre commented on src/app/core/utils/ComponentUtils.ts
> +            for (let w of p.getWires()) {
nit: use `const`

2022-02-24 15:10 UTC, LeonMontealegre commented on src/app/core/tools/handlers/SelectPathHandler.ts
> +        }
Can condense this as
```ts
const path = (wire) ? (GetWirePath(wire)) : (GetComponentPath(component!));
history.add(CreateGroupSelectAction(selections, path).execute());
```

2022-02-24 15:10 UTC, LeonMontealegre commented on src/app/core/tools/handlers/SelectPathHandler.ts
> +            .find(o => o.isWithinSelectBounds(worldMousePos));
Combine these using `getAll()`, which, when reversed, will have the wires in front and the objects at the back which is the desired behavior. (also make sure to cast `as (Component | Wire)`)

Then for the if-statement below, use `(obj instanceof Wire)`

2022-03-18 16:11 UTC, LeonMontealegre requested changes
Just a few nits!

2022-03-18 16:11 UTC, LeonMontealegre commented on src/app/core/tools/handlers/SelectPathHandler.ts
> +        const obj: Component | Wire = designer
nit: Shouldn't need a double cast, the cast below should be enough

2022-03-18 16:11 UTC, LeonMontealegre commented on src/app/core/tools/handlers/SelectPathHandler.ts
> +import {Wire} from "core/models";
nit: Combine these to `import {Component, Wire} from "core/models";` and more the import to be above the ".." import

2022-04-02 22:01 UTC, TGCrystal approved these changes

2022-04-12 20:17 UTC, LeonMontealegre approved these changes

2022-04-18 02:14 UTC, merged