Allow optional disabling of snapping when using the Translate Action
OpenCircuits/OpenCircuits pull request #988
Opened 2022-02-10 20:10 UTC by Cyphecx

Fixes #910
I added an optional "snap" flag to the constructor of the Translate Action. All of the snapping calls are ignored when this is set to false. 
This addresses the issue in #910 by setting the translate constructors snap flag to false in the postion module of the selection pop up. This prevents snapping when making minute adjustments to position in the selection pop up.

2022-02-24 03:46 UTC, TGCrystal requested changes
This fixes the case when editing the value in the text box, but not when holding shift to snap to the grid lines. That snapping behavior is still being overridden by snapping to other port.

2022-02-24 03:46 UTC, TGCrystal commented on src/app/core/actions/transform/TranslateAction.ts
> +        else{ this.snap = snap;}
This syntax can be cleaned up by changing `snap?: boolean` to `snap = true`. Then just `this.snap = snap;` is all that is necessary below.

2022-02-24 03:46 UTC, TGCrystal commented on src/app/core/actions/transform/TranslateAction.ts
> +        }
`{}` are not needed for single line if statements like this one

2022-02-24 03:46 UTC, TGCrystal commented on src/app/core/actions/transform/TranslateAction.ts
> +        }
`{}` are not needed for single line if statements like this one

2022-02-25 21:36 UTC, TGCrystal approved these changes

2022-03-18 16:15 UTC, LeonMontealegre requested changes
just some nits and formatting stuff!

2022-03-18 16:15 UTC, LeonMontealegre commented on src/app/core/actions/transform/TranslateAction.ts
> +        if(this.snap)
nit: space after `if`

2022-03-18 16:15 UTC, LeonMontealegre commented on src/app/core/actions/transform/TranslateAction.ts
> +        if(this.snap)
nit: space after `if`

2022-03-18 16:15 UTC, LeonMontealegre commented on src/app/core/tools/TranslateTool.ts
> +                    const snapping = input.isShiftKeyDown() ? false : true;
This sounds unintuitive because generally holding shift would be snapping, let's call this `snapToConnections`

2022-03-22 18:11 UTC, LeonMontealegre approved these changes

2022-04-02 22:02 UTC, TGCrystal approved these changes

2022-04-18 02:15 UTC, merged