Newhistorybutton
OpenCircuits/OpenCircuits pull request #996
Opened 2022-02-11 22:20 UTC by EricW123

Issue #979  solved.

Added a new history button at top left corner, next to locker button.

2022-02-24 03:17 UTC, TGCrystal commented on src/site/shared/containers/Header/Left/Locker.tsx
> +export const LockToggleButton = () => {
nit: 2 newlines between last import and start of code

2022-02-24 03:21 UTC, TGCrystal requested changes
You will need to adjust the breakpoint for the dropdown arrow in the top right that appears on mobile. As it is now, the top right dropdown buttons disappear at 700px but the arrow dropdown of dropdowns doesn't appear until 600px.

2022-02-24 03:21 UTC, TGCrystal commented on src/site/shared/containers/Header/Left/SideBar.tsx
> +export const SideBarToggleButton = () => {
nit: 2 newlines between last import and start of code

2022-02-24 03:21 UTC, TGCrystal commented on src/site/shared/containers/Header/Left/Locker.tsx
> +		<div>
nit: Move this `<div>` one indentation to the right

2022-02-24 03:21 UTC, TGCrystal commented on src/site/shared/containers/Header/Left/SideBar.tsx
> +		<div>
nit: one indentation to the left

2022-02-24 03:21 UTC, TGCrystal commented on src/site/shared/containers/Header/Left/SideBar.tsx
> +        </div>
nit: one indentation to the right

2022-03-18 16:34 UTC, LeonMontealegre approved these changes

2022-03-18 18:27 UTC, merged